sensors:
  frequency: 10 # Hz
  availableSensors:
    - name: "rgb"
      callback: "RGBACallback"
      publisher: "ImagePublisher"
      topic: "~rgb"
    - name: "depth"
      callback: "depthCallback"
      publisher: "ImagePublisher"
      topic: "~depth"
    - name: "semantic"
      callback: "mono8Callback"
      publisher: "ImagePublisher"
      topic: "~semantic"
  availableCameras:
    - name: "rgb"
      topic: "~rgb/camera"
      width: 256
      height: 256
