ENVIRONMENT:
  MAX_EPISODE_STEPS: 1000
  ITERATOR_OPTIONS:
    MAX_SCENE_REPEAT_STEPS: 50000
SIMULATOR:
  AGENT_0:
    SENSORS: ["RGB_SENSOR", "DEPTH_SENSOR","SEMANTIC_SENSOR"]
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
  RGB_SENSOR:
    WIDTH: 256
    HEIGHT: 256
  DEPTH_SENSOR:
    WIDTH: 256
    HEIGHT: 256
  SEMANTIC_SENSOR:
    WIDTH: 256
    HEIGHT: 256
TASK:
  TYPE: Nav-v0
  SUCCESS_DISTANCE: 1.

  SENSORS: ['IMAGEGOAL_SENSOR']

  MEASUREMENTS: ["DISTANCE_TO_GOAL", "SUCCESS", "SPL", "SOFT_SPL"]
  SUCCESS:
    SUCCESS_DISTANCE: 1.

DATASET:
  TYPE: PointNav-v1
  SPLIT: train
  #DATA_PATH: /home/rene/catkin_ws/src/habitat_ros/data/datasets/pointnav/gibson/v1/{split}/{split}.json.gz
  DATA_PATH: /home/rene/catkin_ws/src/active_learning_for_segmentation/habitat_ros/src/data/datasets/gibson/v1/{split}/{split}.json.gz
